### ISSUE TITLE
_typing.py should be typing.py

### ISSUE THREAD

**Issue by xuhdev** [CODAIT/pardata#129]
We are exposing the annotations in multiple places.

**Comment by edwardleardi** [comment]
Any preference for how to import this to avoid name clashes with python standard library `typing`? Maybe `from . import typing as pydax_typing`?

**Comment by xuhdev** [comment]
You mean for our own use? We can do `from . import typing as typing_`.

**Comment by edwardleardi** [comment]
Yeah for our use. Got it
