### ISSUE TITLE
load_dataset function error when `download = False`

### ISSUE THREAD

**Issue by yil532** [CODAIT/pardata#214]
When using code command `gmb_data = pydax.load_dataset('gmb', version='1.0.2', download=False),` this error message pops up (copied below). Seems like I must put `download = True`. @xuhdev 

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/pydax/_high_level.py", line 197, in load_dataset
    return dataset.load(subdatasets=subdatasets)
  File "/opt/anaconda3/lib/python3.7/site-packages/pydax/_dataset.py", line 215, in load
    raise RuntimeError(f'Downloaded data files are not present in {self._data_dir_} or are corrupted.')
RuntimeError: Downloaded data files are not present in /Users/yiwenli/.pydax/data/default/gmb/1.0.2 or are corrupted.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.7/site-packages/pydax/_high_level.py", line 131, in name_wrapper
    return func(name, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/pydax/_high_level.py", line 154, in version_wrapper
    return func(name=name, version=version, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/pydax/_high_level.py", line 199, in load_dataset
    raise RuntimeError('Failed to load the dataset because some files are not found. '
RuntimeError: Failed to load the dataset because some files are not found. Did you forget to download the dataset (by specifying `download=True`)?
Caused by:
Downloaded data files are not present in /Users/yiwenli/.pydax/data/default/gmb/1.0.2 or are corrupted.

**Comment by xuhdev** [comment]
This is expected. If you have never downloaded the dataset, `download=False` would fail. The error message says:

> RuntimeError: Failed to load the dataset because some files are not found. Did you forget to download the dataset (by specifying download=True)?

**Comment by yil532** [comment]
Oh Gotcha, this is for users who had downloaded the dataset and want to reload and update? My question is: why would they want to run this command line? @xuhdev

**Comment by xuhdev** [comment]
If the user has called `download=True` for once, then they can save the downloading time by specifying `download=False`. This is especially important for large datasets.

**Comment by xuhdev** [comment]
I created #215 to clarify this in the error message and doc.

**Comment by yil532** [comment]
Thanks, Hong for the explanation :) @xuhdev
