### ISSUE TITLE
Have to decide the relationship between `Dataset.load` and `Dataset.is_downloaded`

### ISSUE THREAD

**Issue by xuhdev** [CODAIT/pardata#76]
Should `Dataset.load` call `Dataset.is_downloaded`? Or should we add a parameter to adjust this behavior?

**Comment by edwardleardi** [comment]
Do you mean like adding a parameter like `force_load` to `Dataset.load`? If so, makes sense, you created a pretty thorough implementation of `Dataset.is_downloaded` so it would be good to call it elsewhere in the package.

**Comment by xuhdev** [comment]
Yeah, something like `strict` or `force_check`.

**Comment by edwardleardi** [comment]
Gotcha, yeah I think we can do something like `force_check` which defaults to `True` and if `Dataset.is_downloaded` returns `False` when `Dataset.load` is called we can raise an error. 

Should we do something similar for `Dataset.download`? Use `force_check` which defaults to `True` which raises an error or warning if the user tries to call `Dataset.download` but `Dataset.is_downloaded` returns `True`?

**Comment by xuhdev** [comment]
That's a good point. Yeah, I think that would make sense.

**Comment by edwardleardi** [comment]
Ok cool, can I reserve this issue for myself as well this week?

**Comment by xuhdev** [comment]
Sure, just assign yourself
