### ISSUE TITLE
Dataset.load should return something

### ISSUE THREAD

**Issue by xuhdev** [CODAIT/pardata#79]
For convenience, `Dataset.load` can return `Dataset.data`, if we don't have other things in mind.

**Comment by edwardleardi** [comment]
Other than `Dataset.data` what else would make sense to return?

**Comment by edwardleardi** [comment]
I can work on this one this week

**Comment by xuhdev** [comment]
I don't see anything else to return at this point

**Comment by edwardleardi** [comment]
Ok `Dataset._data` it is then :)
