### ISSUE TITLE
Automatic guess the type of a file and loads it

### ISSUE THREAD

**Issue by xuhdev** [CODAIT/pardata#98]
We can use https://docs.python.org/3/library/mimetypes.html to guess the mime type of a file and choose an appropriate loader. This can potentially significantly broaden our audience base and make our initial marketing of PyDAX much easier, especially at its nascent stage.

**Comment by xuhdev** [comment]
Related to #52

**Comment by edwardleardi** [comment]
Would we use this in the case where a dataset is very simple with just one subdataset (e.g. a single csv file)? Then we wouldn't even need a dataset schema file right?

**Comment by xuhdev** [comment]
Yeah if we don't add any description. We can automatically categorize directories as subdatasets. Datasets such as collections of images should also work (after we have an image loader).

**Comment by xuhdev** [comment]
This has already been done
